name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21' # Use Go 1.21+ for generics support
        cache: true
    
    - name: Install gotestsum
      run: go install gotest.tools/gotestsum@latest
    
    - name: Install gomock (for code generation)
      run: go install go.uber.org/mock/mockgen@latest
    
    - name: Install protoc
      uses: arduino/setup-protoc@v2
      with:
        version: '25.x' # Use a newer version closer to local v32.1
    
    - name: Install protoc-gen-go
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.1
    
    - name: Download dependencies
      run: go mod download
    
    - name: Verify dependencies
      run: go mod verify
    
    - name: Generate code (protobuf and mocks)
      run: go generate ./...
    
    - name: Build
      run: go build -v ./...
    
    - name: Run unit tests
      run: gotestsum --packages="./communities" -f standard-verbose --rerun-fails -- -v -count=1
    
    - name: Check test coverage for communities package
      run: |
        go test -coverprofile=coverage.out ./communities
        go tool cover -func=coverage.out
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false